package selenium.learning;

// Generated by Selenium IDE

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MakemytripTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @BeforeMethod
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterMethod
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void makemytrip() {
    driver.get("https://www.makemytrip.com/");
    driver.manage().window().setSize(new Dimension(1082, 816));
    driver.findElement(By.cssSelector(".swipCircle")).click();
    driver.findElement(By.cssSelector(".searchToCity")).click();
    driver.findElement(By.cssSelector("#react-autowhatever-1-section-0-item-0 .calc60 > .font14")).click();
    driver.findElement(By.cssSelector(".DayPicker-Month:nth-child(2) .DayPicker-Week:nth-child(1) > .DayPicker-Day:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".dates .blackText")).click();
    driver.findElement(By.cssSelector(".DayPicker-Month:nth-child(1) .DayPicker-Week:nth-child(3) > .DayPicker-Day:nth-child(7) > .dateInnerCell")).click();
    driver.findElement(By.cssSelector(".primaryBtn")).click();
    driver.findElement(By.cssSelector(".overlayCrossIcon")).click();
    js.executeScript("window.scrollTo(0,276)");
    driver.findElement(By.cssSelector(".menu_Homestays .chNavText")).click();
    driver.close();
  }
}
